-- MySQL Script generated by MySQL Workbench
-- Fri Dec 17 13:11:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catalog
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `catalog` ;

-- -----------------------------------------------------
-- Schema catalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalog` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `catalog` ;

-- -----------------------------------------------------
-- Table `catalog`.`csm_agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_agent` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_agent` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  `Organization` VARCHAR(50) NULL DEFAULT NULL,
  `Contact` VARCHAR(45) NULL,
  `Notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`cls_tool_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`cls_tool_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`cls_tool_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `descr` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalog`.`csm_business_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_business_service` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_business_service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_methodological_tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_methodological_tool` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_methodological_tool` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Release_Date` date NULL DEFAULT NULL,
  `Description` VARCHAR(1000) NULL DEFAULT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Standard_Istat` TINYINT NULL DEFAULT 0,
  `Tags` VARCHAR(500) NULL DEFAULT NULL,
  `Version` VARCHAR(100) NULL DEFAULT NULL,
  `Tool_type` INT NOT NULL,
  `service` INT NOT NULL,
  `Last_update` date NULL,
  `Requirements`VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_methodological_tool_csm_tool_type1`
    FOREIGN KEY (`Tool_type`)
    REFERENCES `catalog`.`cls_tool_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_methodological_tool_csm_business_service1`
    FOREIGN KEY (`service`)
    REFERENCES `catalog`.`csm_business_service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_methodological_tool_csm_tool_type1_idx` ON `catalog`.`csm_methodological_tool` (`Tool_type` ASC) VISIBLE;

CREATE INDEX `fk_csm_methodological_tool_csm_business_service1_idx` ON `catalog`.`csm_methodological_tool` (`service` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_desktop_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_desktop_application` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_desktop_application` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Download` VARCHAR(100) NULL DEFAULT NULL,
  `Licence` VARCHAR(100) NULL DEFAULT NULL,
  `Language` VARCHAR(100) NULL DEFAULT NULL,
  `Package` VARCHAR(100) NULL DEFAULT NULL,
  `Operative_System` VARCHAR(20) NULL DEFAULT NULL,
  `Version` VARCHAR(45) NULL,
  `Technical_requirements` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_desktop_application_csm_methodological_tool1`
    FOREIGN KEY (`ID`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`cls_document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`cls_document_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`cls_document_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `descr` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalog`.`csm_documentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_documentation` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_documentation` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  `Publisher` VARCHAR(50) NULL DEFAULT NULL,
  `Document_type` INT NULL DEFAULT NULL,
  `Notes` VARCHAR(100) NULL DEFAULT NULL,
  `Resource` VARCHAR(1000) NULL DEFAULT NULL,
  `tool` INT NOT NULL,
  PRIMARY KEY (`ID`, `tool`),
  CONSTRAINT `fk_csm_documentation_csm_methodological_tool1`
    FOREIGN KEY (`tool`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_documentation_csm_document_type1`
    FOREIGN KEY (`Document_type`)
    REFERENCES `catalog`.`cls_document_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_documentation_csm_methodological_tool1_idx` ON `catalog`.`csm_documentation` (`tool` ASC) VISIBLE;

CREATE INDEX `fk_csm_documentation_csm_document_type1_idx` ON `catalog`.`csm_documentation` (`Document_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_agent_tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_agent_tool` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_agent_tool` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `agent` INT NOT NULL,
  `tool` INT NOT NULL,
  `role` VARCHAR(100) NULL DEFAULT NULL,
  `Notes` TEXT NULL DEFAULT NULL,
  `Reference_Date` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`agent`, `tool`),
  CONSTRAINT `fk_CSM_link_Agent_CSM_Methodological_tool`
    FOREIGN KEY (`agent`)
    REFERENCES `catalog`.`csm_agent` (`ID`),
  CONSTRAINT `fk_CSM_link_Agent_tool_CSM_Methodological_Tool`
    FOREIGN KEY (`tool`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_CSM_link_Agent_tool_CSM_Methodological_Tool` ON `catalog`.`csm_link_agent_tool` (`tool` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_software_procedure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_software_procedure` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_software_procedure` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Code` LONGTEXT NULL DEFAULT NULL,
  `Language` VARCHAR(30) NULL DEFAULT NULL,
  `Dependencies` VARCHAR(100) NULL DEFAULT NULL,
  `Technical_Requirements` VARCHAR(100) NULL,
  `Workflow` VARCHAR(45) NULL,
  `Download` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_software_procedure_csm_methodological_tool1`
    FOREIGN KEY (`ID`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_statistical_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_statistical_method` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_statistical_method` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Requirements` TEXT NULL DEFAULT NULL,
  `Assumptions` TEXT NULL DEFAULT NULL,
  `Constraints` TEXT NULL DEFAULT NULL,
  `Notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_statistical_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_statistical_service` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_statistical_service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Protocol` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(100) NULL,
  `Outcomes` VARCHAR(100) NULL,
  `Service_Dependencies` VARCHAR(100) NULL,
  `Restrictions` VARCHAR(100) NULL,
  `GSBPM` VARCHAR(45) NULL,
  `Business_Function` VARCHAR(45) NULL,
  `process_design` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_statistical_service_csm_methodological_tool1`
    FOREIGN KEY (`ID`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_cls_data_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_cls_data_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_cls_data_type` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_parameter` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_parameter` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `DEFAULT_VAL` VARCHAR(50) NULL DEFAULT NULL,
  `JSON_TEMPLATE` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_app_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_app_role` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_app_role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(50) NULL DEFAULT NULL,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `CLS_DATA_TYPE_ID` INT NULL DEFAULT NULL,
  `PARAMETER_ID` INT NULL DEFAULT NULL,
  `HIDDEN` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_app_role_csm_data_type`
    FOREIGN KEY (`CLS_DATA_TYPE_ID`)
    REFERENCES `catalog`.`csm_cls_data_type` (`ID`),
  CONSTRAINT `fk_csm_app_role_csm_paramter`
    FOREIGN KEY (`PARAMETER_ID`)
    REFERENCES `catalog`.`csm_parameter` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 118
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_app_role_csm_data_type` ON `catalog`.`csm_app_role` (`CLS_DATA_TYPE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_app_role_csm_paramter` ON `catalog`.`csm_app_role` (`PARAMETER_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_app_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_app_service` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_app_service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `IMPLEMENTATION_LANGUAGE` VARCHAR(100) NULL DEFAULT NULL,
  `ENGINE` VARCHAR(100) NULL DEFAULT NULL,
  `SOURCE_PATH` VARCHAR(100) NULL DEFAULT NULL,
  `SOURCE_CODE` LONGTEXT NULL DEFAULT NULL,
  `AUTHOR` VARCHAR(100) NULL DEFAULT NULL,
  `LICENCE` VARCHAR(100) NULL DEFAULT NULL,
  `CONTACT` VARCHAR(100) NULL DEFAULT NULL,
  `business_service_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_app_service_csm_business_service1`
    FOREIGN KEY (`business_service_ID`)
    REFERENCES `catalog`.`csm_business_service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 251
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_app_service_csm_business_service1_idx` ON `catalog`.`csm_app_service` (`business_service_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_gsbpm_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_gsbpm_process` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_gsbpm_process` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(10) NULL DEFAULT NULL,
  `NAME` VARCHAR(250) NULL DEFAULT NULL,
  `PHASE` INT NULL DEFAULT NULL,
  `SUBPROCESS` INT NULL DEFAULT NULL,
  `ACTIVE` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_phase_sub_proc`
    FOREIGN KEY (`PHASE`)
    REFERENCES `catalog`.`csm_gsbpm_process` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_gsbpm_process_csm_gsbpm_process` ON `catalog`.`csm_gsbpm_process` (`PHASE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_business_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_business_function` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_business_function` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `LABEL` VARCHAR(50) NULL DEFAULT NULL,
  `ACTIVE` INT NULL DEFAULT NULL,
  `GSBPM_PROCESS_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_business_function_csm_gsbpm_process`
    FOREIGN KEY (`GSBPM_PROCESS_ID`)
    REFERENCES `catalog`.`csm_gsbpm_process` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_business_function_csm_gsbpm_process` ON `catalog`.`csm_business_function` (`GSBPM_PROCESS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_business_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_business_process` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_business_process` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `LABEL` VARCHAR(50) NULL DEFAULT NULL,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `PARENT` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_business_process_csm_business_process`
    FOREIGN KEY (`PARENT`)
    REFERENCES `catalog`.`csm_business_process` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 275
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_business_process_csm_business_process` ON `catalog`.`csm_business_process` (`PARENT` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_cls_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_cls_rule` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_cls_rule` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `NOTE` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_cls_statistical_variable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_cls_statistical_variable` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_cls_statistical_variable` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `TYPE` INT NULL DEFAULT NULL,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `VARIABLE_NAME_ITA` VARCHAR(500) NULL DEFAULT NULL,
  `VARIABLE_NAME_ENG` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_cls_type_io`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_cls_type_io` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_cls_type_io` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_user_roles` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_user_roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_users` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `SURNAME` VARCHAR(100) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(500) NULL DEFAULT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_users_csm_user_roles`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `catalog`.`csm_user_roles` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_users_csm_user_roles` ON `catalog`.`csm_users` (`ROLE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_work_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_work_session` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_work_session` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `LAST_UPDATE` DATETIME NULL DEFAULT NULL,
  `USER_ID` INT NOT NULL,
  `BUSINESS_FUNCTION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_worksession_business_function`
    FOREIGN KEY (`BUSINESS_FUNCTION_ID`)
    REFERENCES `catalog`.`csm_business_function` (`ID`),
  CONSTRAINT `fk_csm_worksession_user`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `catalog`.`csm_users` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_worksession_user` ON `catalog`.`csm_work_session` (`USER_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_worksession_business_function` ON `catalog`.`csm_work_session` (`BUSINESS_FUNCTION_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_data_processing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_data_processing` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_data_processing` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `LAST_UPDATE` DATETIME NULL DEFAULT NULL,
  `BUSINESS_PROCESS_ID` INT NOT NULL,
  `WORK_SESSION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_data_processing_business_process`
    FOREIGN KEY (`BUSINESS_PROCESS_ID`)
    REFERENCES `catalog`.`csm_business_process` (`ID`),
  CONSTRAINT `fk_csm_data_processing_worksession`
    FOREIGN KEY (`WORK_SESSION_ID`)
    REFERENCES `catalog`.`csm_work_session` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_data_processing_business_process` ON `catalog`.`csm_data_processing` (`BUSINESS_PROCESS_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_data_processing_worksession` ON `catalog`.`csm_data_processing` (`WORK_SESSION_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_dataset_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_dataset_file` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_dataset_file` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FILE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `FILE_LABEL` VARCHAR(50) NULL DEFAULT NULL,
  `FILE_FORMAT` VARCHAR(50) NULL DEFAULT NULL,
  `FIELD_SEPARATOR` VARCHAR(50) NULL DEFAULT NULL,
  `TOTAL_ROWS` INT NULL DEFAULT NULL,
  `LAST_UPDATE` DATETIME NULL DEFAULT NULL,
  `CLS_DATA_TYPE_ID` INT NULL DEFAULT NULL,
  `WORK_SESSION_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_datakset_file_data_type`
    FOREIGN KEY (`CLS_DATA_TYPE_ID`)
    REFERENCES `catalog`.`csm_cls_data_type` (`ID`),
  CONSTRAINT `fk_csm_datakset_file_worksession`
    FOREIGN KEY (`WORK_SESSION_ID`)
    REFERENCES `catalog`.`csm_work_session` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_datakset_file_data_type` ON `catalog`.`csm_dataset_file` (`CLS_DATA_TYPE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_datakset_file_worksession` ON `catalog`.`csm_dataset_file` (`WORK_SESSION_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_dataset_column`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_dataset_column` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_dataset_column` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `CONTENT` JSON NULL DEFAULT NULL,
  `CONTENT_SIZE` INT NULL DEFAULT NULL,
  `DATASET_FILE_ID` INT NULL DEFAULT NULL,
  `STATISTICAL_VARIABLE_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_dataset_column_dataset_id`
    FOREIGN KEY (`DATASET_FILE_ID`)
    REFERENCES `catalog`.`csm_dataset_file` (`ID`),
  CONSTRAINT `fk_csm_dataset_column_statistical_variable`
    FOREIGN KEY (`STATISTICAL_VARIABLE_ID`)
    REFERENCES `catalog`.`csm_cls_statistical_variable` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_dataset_column_dataset_id` ON `catalog`.`csm_dataset_column` (`DATASET_FILE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_dataset_column_statistical_variable` ON `catalog`.`csm_dataset_column` (`STATISTICAL_VARIABLE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_function_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_function_process` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_function_process` (
  `BUSINESS_FUNCTION_ID` INT NOT NULL,
  `BUSINESS_PROCESS_ID` INT NOT NULL,
  PRIMARY KEY (`BUSINESS_FUNCTION_ID`, `BUSINESS_PROCESS_ID`),
  CONSTRAINT `fk_csm_bfunc_bprocess_csm_business_function`
    FOREIGN KEY (`BUSINESS_FUNCTION_ID`)
    REFERENCES `catalog`.`csm_business_function` (`ID`),
  CONSTRAINT `fk_csm_bfunc_bprocess_csm_business_process`
    FOREIGN KEY (`BUSINESS_PROCESS_ID`)
    REFERENCES `catalog`.`csm_business_process` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_bfunc_bprocess_csm_business_process` ON `catalog`.`csm_link_function_process` (`BUSINESS_PROCESS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_view_data_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_view_data_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_view_data_type` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_function_view_data_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_function_view_data_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_function_view_data_type` (
  `BUSINESS_FUNCTION_ID` INT NOT NULL,
  `VIEW_DATA_TYPE_ID` INT NOT NULL,
  PRIMARY KEY (`BUSINESS_FUNCTION_ID`, `VIEW_DATA_TYPE_ID`),
  CONSTRAINT `fk_csm_view_data_type_csm_business_function`
    FOREIGN KEY (`BUSINESS_FUNCTION_ID`)
    REFERENCES `catalog`.`csm_business_function` (`ID`),
  CONSTRAINT `fk_csm_view_data_type_csm_view_data_type`
    FOREIGN KEY (`VIEW_DATA_TYPE_ID`)
    REFERENCES `catalog`.`csm_view_data_type` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_view_data_type_csm_view_data_type` ON `catalog`.`csm_link_function_view_data_type` (`VIEW_DATA_TYPE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_process_step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_process_step` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_process_step` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `LABEL` VARCHAR(100) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `BUSINESS_SERVICE_ID` INT NOT NULL,
  `SUBSTEP` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_ITERATE_process_step`
    FOREIGN KEY (`SUBSTEP`)
    REFERENCES `catalog`.`csm_process_step` (`ID`),
  CONSTRAINT `fk_csm_process_step_business_service`
    FOREIGN KEY (`BUSINESS_SERVICE_ID`)
    REFERENCES `catalog`.`csm_business_service` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_process_step_business_service` ON `catalog`.`csm_process_step` (`BUSINESS_SERVICE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_ITERATE_process_step` ON `catalog`.`csm_process_step` (`SUBSTEP` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_process_step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_process_step` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_process_step` (
  `BUSINESS_PROCESS_ID` INT NOT NULL,
  `PROCESS_STEP_ID` INT NOT NULL,
  PRIMARY KEY (`BUSINESS_PROCESS_ID`, `PROCESS_STEP_ID`),
  CONSTRAINT `fk_csm_bprocess_bstep_csm_business_process`
    FOREIGN KEY (`BUSINESS_PROCESS_ID`)
    REFERENCES `catalog`.`csm_business_process` (`ID`),
  CONSTRAINT `fk_csm_bprocess_bstep_csm_process_step`
    FOREIGN KEY (`PROCESS_STEP_ID`)
    REFERENCES `catalog`.`csm_process_step` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_bprocess_bstep_csm_process_step` ON `catalog`.`csm_link_process_step` (`PROCESS_STEP_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_step_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_step_instance` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_step_instance` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `METHOD` VARCHAR(50) NULL DEFAULT NULL,
  `STATMETHOD` INT NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `FUNCTIONALITY` VARCHAR(50) NULL DEFAULT NULL,
  `APP_SERVICE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_step_instance_csm_app_service`
    FOREIGN KEY (`APP_SERVICE_ID`)
    REFERENCES `catalog`.`csm_app_service` (`ID`),
  CONSTRAINT `fk_csm_step_instance_csm_statistical_method1`
    FOREIGN KEY (`STATMETHOD`)
    REFERENCES `catalog`.`csm_statistical_method` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_step_instance_csm_app_service` ON `catalog`.`csm_step_instance` (`APP_SERVICE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_instance_csm_statistical_method1_idx` ON `catalog`.`csm_step_instance` (`METHOD` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_step_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_step_instance` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_step_instance` (
  `PROCESS_STEP_ID` INT NOT NULL,
  `PROCESS_STEP_INSTANCE_ID` INT NOT NULL,
  PRIMARY KEY (`PROCESS_STEP_ID`, `PROCESS_STEP_INSTANCE_ID`),
  CONSTRAINT `fk_csm_step_instance_process_step`
    FOREIGN KEY (`PROCESS_STEP_ID`)
    REFERENCES `catalog`.`csm_process_step` (`ID`),
  CONSTRAINT `fk_csm_step_instance_step_instance`
    FOREIGN KEY (`PROCESS_STEP_INSTANCE_ID`)
    REFERENCES `catalog`.`csm_step_instance` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_step_instance_step_instance` ON `catalog`.`csm_link_step_instance` (`PROCESS_STEP_INSTANCE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_log` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_log` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MSG` TEXT NULL DEFAULT NULL,
  `MSG_TIME` DATETIME NULL DEFAULT NULL,
  `TYPE` VARCHAR(50) NULL DEFAULT NULL,
  `WORK_SESSION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_log_worksession`
    FOREIGN KEY (`WORK_SESSION_ID`)
    REFERENCES `catalog`.`csm_work_session` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_log_worksession` ON `catalog`.`csm_log` (`WORK_SESSION_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_ruleset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_ruleset` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_ruleset` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FILE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `FILE_LABEL` VARCHAR(50) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `RULES_TOTAL` INT NULL DEFAULT NULL,
  `LAST_UPDATE` DATETIME NULL DEFAULT NULL,
  `WORK_SESSION_ID` INT NOT NULL,
  `DATASET_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_ruleset_dataset`
    FOREIGN KEY (`DATASET_ID`)
    REFERENCES `catalog`.`csm_dataset_file` (`ID`),
  CONSTRAINT `fk_ruleset_work_session`
    FOREIGN KEY (`WORK_SESSION_ID`)
    REFERENCES `catalog`.`csm_work_session` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_ruleset_work_session` ON `catalog`.`csm_ruleset` (`WORK_SESSION_ID` ASC) VISIBLE;

CREATE INDEX `fk_ruleset_dataset` ON `catalog`.`csm_ruleset` (`DATASET_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_rule` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_rule` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `CODE` VARCHAR(50) NULL DEFAULT NULL,
  `DESCR` TEXT NULL DEFAULT NULL,
  `BLOCKING` INT NULL DEFAULT NULL,
  `ERROR_CODE` INT NULL DEFAULT NULL,
  `ACTIVE` INT NULL DEFAULT NULL,
  `RULE` TEXT NULL DEFAULT NULL,
  `VARIABLE_ID` INT NULL DEFAULT NULL,
  `CLS_RULE_ID` INT NOT NULL,
  `RULESET_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_rule_cls_rule`
    FOREIGN KEY (`CLS_RULE_ID`)
    REFERENCES `catalog`.`csm_cls_rule` (`ID`),
  CONSTRAINT `fk_rule_ruleset`
    FOREIGN KEY (`RULESET_ID`)
    REFERENCES `catalog`.`csm_ruleset` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_rule_cls_rule` ON `catalog`.`csm_rule` (`CLS_RULE_ID` ASC) VISIBLE;

CREATE INDEX `fk_rule_ruleset` ON `catalog`.`csm_rule` (`RULESET_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_step_instance_signature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_step_instance_signature` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_step_instance_signature` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `REQUIRED` TINYINT NULL DEFAULT NULL,
  `APP_ROLE_ID` INT NOT NULL,
  `STEP_INSTANCE_ID` INT NOT NULL,
  `CLS_TYPE_IO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_step_instance_signature_csm_app_role`
    FOREIGN KEY (`APP_ROLE_ID`)
    REFERENCES `catalog`.`csm_app_role` (`ID`),
  CONSTRAINT `fk_csm_step_instance_signature_csm_step_instance`
    FOREIGN KEY (`STEP_INSTANCE_ID`)
    REFERENCES `catalog`.`csm_step_instance` (`ID`),
  CONSTRAINT `fk_csm_step_instance_signature_csm_type_io`
    FOREIGN KEY (`CLS_TYPE_IO_ID`)
    REFERENCES `catalog`.`csm_cls_type_io` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 216
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_step_instance_signature_csm_app_role` ON `catalog`.`csm_step_instance_signature` (`APP_ROLE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_instance_signature_csm_step_instance` ON `catalog`.`csm_step_instance_signature` (`STEP_INSTANCE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_instance_signature_csm_type_io` ON `catalog`.`csm_step_instance_signature` (`CLS_TYPE_IO_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_workset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_workset` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_workset` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `DATASET_COLUMN` INT NULL DEFAULT NULL,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `CONTENT` JSON NULL DEFAULT NULL,
  `CONTENT_SIZE` INT NULL DEFAULT NULL,
  `VALUE_PARAMETER` LONGTEXT NULL DEFAULT NULL,
  `CLS_DATA_TYPE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_workset_data_type`
    FOREIGN KEY (`CLS_DATA_TYPE_ID`)
    REFERENCES `catalog`.`csm_cls_data_type` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_workset_data_type` ON `catalog`.`csm_workset` (`CLS_DATA_TYPE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_step_runtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_step_runtime` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_step_runtime` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORDER_CODE` INT NULL DEFAULT NULL,
  `ROLE_GROUP` INT NULL DEFAULT NULL,
  `DATA_PROCESSING_ID` INT NOT NULL,
  `WORKSET_ID` INT NOT NULL,
  `APP_ROLE_ID` INT NOT NULL,
  `CLS_DATA_TYPE_ID` INT NOT NULL,
  `CLS_TYPE_IO_ID` INT NOT NULL,
  `STEP_INSTANCE_SIGNATURE_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_app_role`
    FOREIGN KEY (`APP_ROLE_ID`)
    REFERENCES `catalog`.`csm_app_role` (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_data_processing`
    FOREIGN KEY (`DATA_PROCESSING_ID`)
    REFERENCES `catalog`.`csm_data_processing` (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_data_type`
    FOREIGN KEY (`CLS_DATA_TYPE_ID`)
    REFERENCES `catalog`.`csm_cls_data_type` (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_signature`
    FOREIGN KEY (`STEP_INSTANCE_SIGNATURE_ID`)
    REFERENCES `catalog`.`csm_step_instance_signature` (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_type_io`
    FOREIGN KEY (`CLS_TYPE_IO_ID`)
    REFERENCES `catalog`.`csm_cls_type_io` (`ID`),
  CONSTRAINT `fk_csm_step_runtime_csm_workset`
    FOREIGN KEY (`WORKSET_ID`)
    REFERENCES `catalog`.`csm_workset` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_step_runtime_csm_data_processing` ON `catalog`.`csm_step_runtime` (`DATA_PROCESSING_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_runtime_csm_workset` ON `catalog`.`csm_step_runtime` (`WORKSET_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_runtime_csm_app_role` ON `catalog`.`csm_step_runtime` (`APP_ROLE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_runtime_csm_data_type` ON `catalog`.`csm_step_runtime` (`CLS_DATA_TYPE_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_runtime_csm_type_io` ON `catalog`.`csm_step_runtime` (`CLS_TYPE_IO_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_step_runtime_csm_signature` ON `catalog`.`csm_step_runtime` (`STEP_INSTANCE_SIGNATURE_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_workflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_workflow` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_workflow` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RULE_ID` INT NOT NULL,
  `STEP` INT NOT NULL,
  `SUB_STEP` INT NOT NULL,
  `ELSE_STEP` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `catalog`.`cls_design_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`cls_design_type` ;

CREATE TABLE IF NOT EXISTS `catalog`.`cls_design_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalog`.`csm_information_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_information_object` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_information_object` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `descr` VARCHAR(45) NULL,
  `csm_app_role_ID` INT NOT NULL,
  `csm_business_service_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `csm_business_service_ID`),
  CONSTRAINT `fk_csm_information_object_csm_app_role1`
    FOREIGN KEY (`csm_app_role_ID`)
    REFERENCES `catalog`.`csm_app_role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_information_object_csm_business_service1`
    FOREIGN KEY (`csm_business_service_ID`)
    REFERENCES `catalog`.`csm_business_service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_csm_information_object_csm_app_role1_idx` ON `catalog`.`csm_information_object` (`csm_app_role_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_information_object_csm_business_service1_idx` ON `catalog`.`csm_information_object` (`csm_business_service_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_process_design`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_process_design` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_process_design` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `step` INT NOT NULL,
  `type` INT NOT NULL,
  `csm_information_object_id` INT NOT NULL,
  CONSTRAINT `fk_csm_process_design_csm_process_step1`
    FOREIGN KEY (`step`)
    REFERENCES `catalog`.`csm_process_step` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_process_design_csm_design_type1`
    FOREIGN KEY (`type`)
    REFERENCES `catalog`.`cls_design_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_process_design_csm_information_object1`
    FOREIGN KEY (`csm_information_object_id`)
    REFERENCES `catalog`.`csm_information_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_csm_process_design_csm_process_step1_idx` ON `catalog`.`csm_process_design` (`step` ASC) VISIBLE;

CREATE INDEX `fk_csm_process_design_csm_design_type1_idx` ON `catalog`.`csm_process_design` (`type` ASC) VISIBLE;

CREATE INDEX `fk_csm_process_design_csm_information_object1_idx` ON `catalog`.`csm_process_design` (`csm_information_object_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_link_method_tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_method_tool` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_method_tool` (
  `method` INT NOT NULL,
  `tool` INT NOT NULL,
  PRIMARY KEY (`method`, `tool`),
  CONSTRAINT `fk_csm_link_method_tool_csm_methodological_tool1`
    FOREIGN KEY (`tool`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_link_method_tool_csm_statistical_method1`
    FOREIGN KEY (`method`)
    REFERENCES `catalog`.`csm_statistical_method` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_csm_link_method_tool_csm_methodological_tool1_idx` ON `catalog`.`csm_link_method_tool` (`tool` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_tool_gsbpm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_tool_gsbpm` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_tool_gsbpm` (
  `tool` INT NULL,
  `gsbpm` INT NULL,
  CONSTRAINT `fk_csm_tool_gsbpm_csm_methodological_tool1`
    FOREIGN KEY (`tool`)
    REFERENCES `catalog`.`csm_methodological_tool` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_tool_gsbpm_csm_gsbpm_process1`
    FOREIGN KEY (`gsbpm`)
    REFERENCES `catalog`.`csm_gsbpm_process` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_tool_gsbpm_csm_methodological_tool1_idx` ON `catalog`.`csm_tool_gsbpm` (`tool` ASC) VISIBLE;

CREATE INDEX `fk_csm_tool_gsbpm_csm_gsbpm_process1_idx` ON `catalog`.`csm_tool_gsbpm` (`gsbpm` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `catalog`.`csm_business_service_has_csm_app_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalog`.`csm_link_business_service_app_role` ;

CREATE TABLE IF NOT EXISTS `catalog`.`csm_link_business_service_app_role` (
  `business_service_ID` INT NOT NULL,
  `app_role_ID` INT NOT NULL,  
  PRIMARY KEY (`business_service_ID`, `app_role_ID`),
  CONSTRAINT `fk_csm_business_service_has_csm_app_role_business_service1`
    FOREIGN KEY (`business_service_ID`)
    REFERENCES `catalog`.`csm_business_service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_csm_business_service_has_csm_app_role_app_role1`
    FOREIGN KEY (`app_role_ID`)
    REFERENCES `catalog`.`csm_app_role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_csm_business_service_has_csm_app_role_csm_app_role1_idx` ON `catalog`.`csm_link_business_service_app_role` (`app_role_ID` ASC) VISIBLE;

CREATE INDEX `fk_csm_business_service_has_csm_app_role_csm_business_servi_idx` ON `catalog`.`csm_link_business_service_app_role` (`business_service_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
