-- 
-- USER ROLE
-- 
CREATE TABLE PD_RSA_SPER.WP1_user_roles (
  ID 	 	NUMBER NOT NULL ,
  ROLE 	VARCHAR2(50) NULL DEFAULT NULL,
)

-- 
-- USER
-- 
CREATE TABLE PD_RSA_SPER.WP1_users (
  ID 			NUMBER NOT NULL ,
  EMAIL 		VARCHAR2(255) NULL,
  NAME 		VARCHAR2(100) NULL,
  SURNAME 	VARCHAR2(100) NULL,
  PASSWORD 	VARCHAR2(500) NULL,
  ROLE_ID 	NUMBER NOT NULL
  
)
