security:
  secret-key: is2-secretkey
server:
  port: 9080
spring:
  application:
    name: catalog-api-gateway
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/catalogsv?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootmec
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000 #important
  routes:
    service_catalogue:
      path: /api/catalog/**
      url: http://localhost:9081/catalog
      
    service_users:
      path: /api/user/**
      url: http://localhost:8082/user

ribbon:
  eureka:
    enabled: true  #important
  ReadTimeout: 60000
  ConnectTimeout: 60000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #important
