name: Upgrade Catalogo BE Service
on:
  workflow_dispatch:

jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IS2_HOST }}
          username: ${{ secrets.IS2_USERNAME }}
          password: ${{ secrets.IS2_PASSWORD }}
          port: ${{ secrets.IS2_PORT }}
          script: sh /home/is2admin/upgradeCatalogoBEServiceDEV.sh ${{ steps.get_version.outputs.VERSION }}
